### PR TITLE
Isolate couch_log from backend for unit testing

### PR DESCRIPTION
**Pull request by eiri**
This addresses the same issue fixed by latest @rnewson commit, just takes less integration testing and more unit testing approach.

### CODE REVIEW

**Comment by rnewson** [comment]
oh, interesting. Hm, but why not use meck to mock the backend and then assert that it was called?

**Comment by eiri** [comment]
@rnewson this is a fair idea, I'll do that.

**Comment by rnewson** [comment]
This constructs a mock backend but does not confirm the behavior we want. We want to check that couch_log:X("", []) invokes backend_module:X("", []) for each level (and nothing else).

**Comment by eiri** [comment]
you mean we want to assert the whole history of the calls, not just the last call as it is right now?

**Comment by rnewson** [comment]
No, I mean each test should have a mock backend that verifies what we expect to happen for that test;

```
meck:expect(couch_log_eunit, debug, 2, ok),
?assertEqual(ok, couch_log:debug("message", [])),
meck:validate()
```

**Comment by eiri** [comment]
Hm, `meck:validate/1` just checks if the whole mocked module has been used according to its expectations, i.e. that there was no calls with a wrong number of arguments or calls to non-existing function etc.

I guess I can wrap each log level into its own suite with meck's load, expect, assert, validate and unload to ensure that we are calling backend's `X` function and nothing else, but my current test pretty much does the same thing, just with less typing and bonus of validating that we are not doing the double calls.

**Comment by rnewson** [comment]
you say 'just', but that's the entire point of mock objects. :)

Are you saying that meck as I sketched would allow multiple calls to couch_log_eunit:warning/2 even though I said we :expect only one?

**Comment by eiri** [comment]
Well, yes:
```
Eshell V5.8.2  (abort with ^G)
1> meck:new(couch_log_eunit, [non_strict]).
ok
2> meck:expect(couch_log_eunit, debug, 2, ok).
ok
3> couch_log_eunit:debug(a, b).
ok
4> couch_log_eunit:debug(a, b).
ok
5> meck:validate(couch_log_eunit).
true
```

Meck's `expect` lays out a contract, not defines the usage flow and meck's `validate` "just" confirms that that contract been respected, but not asserts in which fashion :)

**Comment by rnewson** [comment]
oh, that's ... terrible.

**Comment by rnewson** [comment]
still, it's better than allowing calls to :warning when we're testing :debug.

**Comment by eiri** [comment]
@rnewson yes, meck does invalidate on none-expected calls, yet to get that behaviour the whole mocked module will need to be loaded and then unloaded for each severity, I haven't seen a way to make already mocked function 'unexpected'.

My test based on validating of the whole history and checks that we are doing exactly right calls and doing them exactly once.

**Comment by rnewson** [comment]
Yes, agreed, I finally see it. +1.

**Pull request merged**
